# Generated by Django 6.0.6 on 2026-06-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicle_current_odometer_vehicle_engine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePnL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_advances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toll_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tyre_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_trips', models.IntegerField(default=0)),
                ('avg_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fuel_efficiency_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pnl', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'period_start', 'period_end'], name='analytics_v_vehicle_d0f36d_idx')],
            },
        ),
    ]
