# Generated by Django 6.0.6 on 2026-06-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('vehicles', '0002_vehicle_current_odometer_vehicle_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepnl',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_records', to='vehicles.vehicle'),
        ),
    ]
