# Generated by Django 6.0.6 on 2026-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='entry_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('PARKING', 'Parking'), ('REPAIR', 'Repair'), ('LOADING', 'Loading'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
