# Generated by Django 6.0.6 on 2026-06-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_vehicle'),
        ('trips', '0002_remove_trip_fuel_cost_remove_trip_user_and_more'),
        ('vehicles', '0002_vehicle_current_odometer_vehicle_engine_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fuel_station',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG')], default='DIESEL', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_extracted',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='odometer_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('REPAIR', 'Repair/Maintenance'), ('TYRE', 'Tyres'), ('OIL', 'Engine Oil'), ('SERVICE', 'Scheduled Service'), ('LOADING', 'Loading/Unloading'), ('PARKING', 'Parking'), ('FOOD', 'Food/Dhaba'), ('FINES', 'Fines/Challan'), ('INSURANCE', 'Insurance Premium'), ('OTHER', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='entry_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=7),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle'),
        ),
    ]
