# Generated by Django 5.0.6 on 2026-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_fuel_station_expense_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('REPAIR', 'Repair/Maintenance'), ('TYRE', 'Tyres'), ('OIL', 'Engine Oil'), ('SERVICE', 'Scheduled Service'), ('LOADING', 'Loading/Unloading'), ('PARKING', 'Parking'), ('FOOD', 'Food/Dhaba'), ('FINES', 'Fines/Challan'), ('INSURANCE', 'Insurance Premium'), ('FREIGHT', 'Freight'), ('OTHER', 'Other')], max_length=15),
        ),
    ]
