# Generated by Django 6.0.6 on 2026-06-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('TE', 'Telugu'), ('TA', 'Tamil'), ('KN', 'Kannada'), ('MR', 'Marathi'), ('BN', 'Bengali'), ('ML', 'Malayalam')], default='EN', max_length=10),
        ),
    ]
