# Generated by Django 6.0.6 on 2026-06-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicle_current_odometer_vehicle_engine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ENGINE_OIL', 'Engine Oil Change'), ('GEAR_OIL', 'Gear Oil'), ('COOLANT', 'Coolant'), ('FILTER_AIR', 'Air Filter'), ('FILTER_DIESEL', 'Diesel Filter'), ('FILTER_OIL', 'Oil Filter'), ('TYRE_ROTATION', 'Tyre Rotation'), ('BRAKE_CHECK', 'Brake Check'), ('GREASING', 'Greasing'), ('FULL_SERVICE', 'Full Service')], max_length=20)),
                ('interval_km', models.IntegerField()),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('last_done_odometer', models.IntegerField(default=0)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_due_odometer', models.IntegerField(default=0)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue')], default='OK', max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ENGINE_OIL', 'Engine Oil Change'), ('GEAR_OIL', 'Gear Oil'), ('COOLANT', 'Coolant'), ('FILTER_AIR', 'Air Filter'), ('FILTER_DIESEL', 'Diesel Filter'), ('FILTER_OIL', 'Oil Filter'), ('TYRE_ROTATION', 'Tyre Rotation'), ('BRAKE_CHECK', 'Brake Check'), ('GREASING', 'Greasing'), ('FULL_SERVICE', 'Full Service')], max_length=20)),
                ('odometer', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workshop', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('service_date', models.DateField()),
                ('next_due_odometer', models.IntegerField(blank=True, null=True)),
                ('receipt_image', models.FileField(blank=True, null=True, upload_to='maintenance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenanceschedule')),
            ],
        ),
    ]
