# Generated by Django 6.0.6 on 2026-06-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_health_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('last_checkup', models.DateField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='drivers.driver')),
            ],
        ),
    ]
