# Generated by Django 6.0.6 on 2026-06-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='documents.document')),
            ],
        ),
    ]
