# Generated by Django 6.0.6 on 2026-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('PETROL', 'Petrol')], default='DIESEL', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='expected_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_tank_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='puc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TRUCK', 'Truck (10-16T)'), ('HEAVY_TRUCK', 'Heavy Truck (16-25T)'), ('TRAILER', 'Trailer (25T+)'), ('LCV', 'LCV (3.5-7.5T)'), ('TAXI', 'Taxi/Car'), ('AUTO', 'Auto Rickshaw')], max_length=20),
        ),
    ]
