# Generated by Django 6.0.6 on 2026-06-10 06:42

import core_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LICENSE', 'Driving License'), ('RC', 'Registration Certificate'), ('INSURANCE', 'Insurance'), ('PUC', 'Pollution Under Control'), ('PERMIT', 'Permit'), ('FITNESS', 'Fitness Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('file_url', models.FileField(upload_to='documents/', validators=[core_validators.validate_file_extension])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
    ]
