# Generated by Django 6.0.6 on 2026-06-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('EXPIRING_SOON', 'Expiring Soon'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20),
        ),
    ]
