# Generated by Django 6.0.6 on 2026-06-10 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('WARNING', 'Warning'), ('HIGH', 'High Risk')], default='SAFE', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
